[package]
name = "uuid-utils"
version = "0.3.0"
edition = "2021"

[lib]
name = "uuid_utils"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.2", features = ["extension-module"] }
uuid = { version = "1.3.0", features = ["v1", "v3", "v4", "v5", "v6", "v7", "v8", "fast-rng"]}
