site_name: UUID-Utils
site_description: Fast, drop-in replacement for Python's uuid module, powered by Rust.
site_url: https://aminalaee.github.io/uuid-utils

theme:
  name: "material"
  palette:
    primary: white
  features:
    - content.code.copy

repo_name: aminalaee/uuid-utils
repo_url: https://github.com/aminalaee/uuid-utils
edit_uri: ""

nav:
  - Introduction: "index.md"
  - API: "api.md"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences

watch:
  - python/

plugins:
  - search

extra:
  analytics:
    provider: google
    property: G-MV427T1Z9X
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aminalaee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amin-alaee
